const job_listings = [
	{
		position: "Kitchen Staff",
		location: "Edmonton",
		description:
			"Do you have what it takes to make sushi?  Here's an opportunity for you to work in a fast-paced environment, with amazing people while making delicious food!",
		wage: 15,
		skills: [
			"Attention to detail",
			"Able to work in a fast-paced environment",
			"Able to multitask, prioritize, and manage time efficiently",
			"Physical endurance to stand for an entire shift",
			"Self-motivated and self-directed",
			"Able to quickly memorize complex or multiple orders",
			"Able to cooperate with others",
			"Able to bend, move, and lift up to 25 pounds or more",
			"Legally able to work in establishments which serve alcohol",
			"Must pass a background check",
			"Able to work early mornings, nights, and weekends",
		],
		experience: [
			"Professional or personal experience is an asset.",
			"High school degree or equivalent",
		],
		url: "https://forms.gle/wmsfXyvsBHNDEGcM9",
		date: "June 24, 2021",
		availability: "Full Time",
		duties: [
			"Setting up, cleaning, and organizing work stations",
			"Preparing ingredients for the shift; washing vegetables, chopping, handling raw fish, cooking rice, etc.",
			"Preparing oven, utensils, and grill for shift",
			"Taking orders from wait staff or computerized system",
			"Cooking order according to food health and safety standards",
			"Recommending ideas for specials or seasonal dishes",
			"Handling multiple food orders at one time",
			"Monitoring multiple food orders as new orders arrive",
			"Dressing order for presentation",
			"Ensuring each guest order has the correct food and sides",
			"Delivering food order to wait staff in a timely manner",
			"Storing all food properly",
			"Sanitizing and cleaning work stations and utensils",
			"Reordering stock and food supplies",
			"Monitoring other cooks and team members",
			"Assisting other cooks in preparing food or helping other team members when needed",
		],
		id: 1,
	},
	{
		position: "Waiter",
		location: "Edmonton",
		description:
			"Do you enjoy serving others?  Here's an opportunity for you to make someone's day / night and serve meals to hungry patrons!",
		wage: 15,
		skills: [
			"Attention to detail",
			"ability to multi-task",
			"able to lift 30-50lbs",
			"Able to handle point of sale systems",
			"Attention to cleanliness and safety",
			"Patience and customer-oriented approach",
			"Excellent communcation skills with a friendly attitude",
			"Responsible and trustworthy",
		],
		experience: [
			"Professional or personal experience is an asset.",
			"High school degree or equivalent is an asset but not required",
		],

		url: "https://forms.gle/fLsyXzDYvP3Bi6hD8",
		date: "June 24, 2021",
		id: 2,
		availability: "Full Time",
		duties: [
			"Prepare restaurant tables with special attention to sanitation and order",
			"Attend to customers upon entrance",
			"Present restaurant menus and help customers select food and/or beverages",
			"Take and serve orders",
			"Answer questions or make recommendations for complementary products",
			"Collaborate with other restaurant servers and kitchen staff",
			"Provide solutions for customer complaints",
			"Issue bills and accept payments",
		],
	},
	{
		position: "Waiter",
		location: "Whitecourt",
		description:
			"Do you enjoy serving others?  Here's an opportunity for you to make someone's day / night and serve meals to hungry patrons!",
		wage: 15,
		skills: [
			"Attention to detail",
			"ability to multi-task",
			"able to lift 30-50lbs",
			"Able to handle point of sale systems",
			"Attention to cleanliness and safety",
			"Patience and customer-oriented approach",
			"Excellent communcation skills with a friendly attitude",
			"Responsible and trustworthy",
		],
		experience: [
			"Professional or personal experience is an asset.",
			"High school degree or equivalent is an asset but not required",
		],

		url: "",
		date: "June 24, 2021",
		id: 3,
		availability: "Full Time",
		duties: [
			"Prepare restaurant tables with special attention to sanitation and order",
			"Attend to customers upon entrance",
			"Present restaurant menus and help customers select food and/or beverages",
			"Take and serve orders",
			"Answer questions or make recommendations for complementary products",
			"Collaborate with other restaurant servers and kitchen staff",
			"Provide solutions for customer complaints",
			"Issue bills and accept payments",
		],
	},
];

export default function getListings() {
	return job_listings;
}
