export default function getServices(service) {
	const services = [
		{
			title: "Optimized Funnels",
			activityScope: [
				"Redesign & convert every page of your existing Funnel into NextJS web apps",
				"Convert pages from ClickFunnels, DropFunnels, LeadPages, or your preferred funnel builder.",
				"Integrate with any marketing software that has an api",
				"Speed up page load times",
				"Analytics integration(s) like Google / Facebook",
				"Optional: Rebounce validation to protect your email sender reputation",
			],
			price: 4999,
			billingFrequency: "Project",
			callType: "strategy",
			url: "https://1lzc663dj0j.typeform.com/to/kZgfh0vi#type=Optimized%20Funnels",
		},
		{
			title: "Scalable Web App",
			activityScope: [
				"Everything in Basic Website Plus:",
				"Ready to scale to 1,000,000+ users",
				"Additional pricing per user per month",
				"Custom admin & staff tools",
				"Custom User Experience",
				"Secure customer one time or subscription payments with Stripe, PayPal, or Crypto",
				"Facebook & Google Analytics Integration",
				"Third Party API Integration",
			],
			price: 1000,
			callType: "strategy",
			billingFrequency: "Project",
			url: "https://1lzc663dj0j.typeform.com/to/LKYTNsVm?type=Progressive%20Web%20App%20Development",
		},
		{
			title: "Basic Website",
			activityScope: [
				"3 months of Project Management",
				"Target Result Alignment",
				"Rapid Prototyping",
				"Scalable Backend",
				"Mobile Responsive",
				"Up to 5 Pages",
				"Custom Solution",
				"You own the source code",
				"Includes 3 months of IT Support",
				"Free web domain for new websites",
			],
			price: 4999,
			billingFrequency: "Project",
			callType: "strategy",
			url: "https://1lzc663dj0j.typeform.com/to/LKYTNsVm?type=Basic%20Website",
		},
		{
			title: "Project Management",
			activityScope: [
				"Planning and Organizing",
				"Managing Tasks",
				"Budget & Cost Management",
				"Task Prioritization",
				"Task Delegation",
			],
			price: 1499,
			billingFrequency: "Project",
			callType: "consultation",
			url: "https://1lzc663dj0j.typeform.com/to/AmQ3HE5S?type=Project%20Management",
		},
		{
			title: "Code Maintenance",
			activityScope: [
				"Optimize and maintain your existing code",
				"Dedicated support line",
				"Dedicated account manager",
				"Domain, hosting, & marketing analytic integrations management",
				"Third party web tool support",
			],
			price: 1499,
			callType: "consultation",
			billingFrequency: "Month",
			url: "https://1lzc663dj0j.typeform.com/to/dAjo78l6#type=Project%20Management",
		},
		{
			title: "Online Presence and Reputation Management",
			activityScope: [
				"Create & Maintain your online business listings",
				"Rank your location higher in Google Business listings",
				"Continuously gather new customer reviews & feedback",
				"Branding",
				"Graphic design",
			],
			price: 399,
			callType: "consultation",
			billingFrequency: "Month",
			url: "https://1lzc663dj0j.typeform.com/to/dAjo78l6#type=Reputation%20Management",
		},
		{
			title: "Search Engine Optimization (SEO)",
			activityScope: [
				"Rank your website higher in Google search listings",
				"Increase organic traffic to your website",
				"Add to your bottom line naturally",
			],
			price: 2499,
			callType: "consultation",
			billingFrequency: "Project",
			url: "https://1lzc663dj0j.typeform.com/to/dAjo78l6#type=Search%20Engine%20Optimization",
		},
		{
			title: "Pay Per Click Advertising (PPC)",
			activityScope: [
				"Attract new ideal clients predictably",
				"Set your own advertising budget",
				"Includes one free 60-second promo video a month",
			],
			price: 1999,
			callType: "consultation",
			billingFrequency: "Month",
			url: "https://1lzc663dj0j.typeform.com/to/dAjo78l6#type=Pay%20Per%20Click",
		},
		// {
		// 	title: "Premium IT Support",
		// 	activityScope: [
		// 		"Everything in Basic IT Support plus",
		// 		"End Customer Support (Up to 300 tickets/mo)",
		// 		"$4.99 per end customer ticket afterwards",
		// 	],
		// 	price: 999,
		// 	billingFrequency: "Month",
		// 	url: "https://1lzc663dj0j.typeform.com/to/WG9nUCJE?type=Premium%20IT%20Support",
		// },
		// {
		// 	title: "Basic IT Support",
		// 	activityScope: [
		// 		"Staff Support",
		// 		"Web Master Support",
		// 		"Technical Troubleshooting",
		// 		"Dedicated Slack Channel",
		// 		"Covered from 9am to 5pm MST",
		// 	],
		// 	price: 299,
		// 	billingFrequency: "Month",
		// 	url: "https://1lzc663dj0j.typeform.com/to/WG9nUCJE?type=Basic%20IT%20Support",
		// },
	];
	return services;
}
